apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
      queryTimeout: 60s
      httpMethod: POST
    secureJsonData:
      httpHeaderValue1: 'Bearer your_token_here'

  - name: Prometheus-Worker3
    type: prometheus
    access: proxy
    url: http://worker3-simulator:9100
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 10s

  - name: TestData
    type: testdata
    access: proxy
    isDefault: false