steps:
  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/shopify-mcp-server:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/shopify-mcp-server:latest'
      - '.'
    dir: 'backend'

  # イメージのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/shopify-mcp-server'

  # Cloud Runへのデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'shopify-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/shopify-mcp-server:$SHORT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8000'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--update-env-vars'
      - 'SHOPIFY_API_VERSION=2024-01'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY