global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'shopify-integration'
    environment: 'production'

rule_files:
  - '/etc/prometheus/alerts.yml'

scrape_configs:
  - job_name: 'shopify-integration-api'
    static_configs:
      - targets: ['integration-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
