name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        playwright install --with-deps
    - name: Run E2E tests
      env:
        E2E_BASE_URL: ${{ vars.E2E_BASE_URL || 'http://localhost:8000' }}
      run: |
        # Start the application in background if running locally
        if [ -z "${{ vars.E2E_BASE_URL }}" ]; then
          python -m src.main &
          APP_PID=$!
          # Wait for app to start
          sleep 10
        fi
        
        python -m pytest tests/e2e -v --html=e2e-report.html || EXIT_CODE=$?
        
        # Stop the application if we started it
        if [ -n "$APP_PID" ]; then
          kill $APP_PID || true
        fi
        
        exit ${EXIT_CODE:-0}
    - name: Upload E2E report
      uses: actions/upload-artifact@v3
      with:
        name: e2e-report
        path: e2e-report.html
