name: Minimal CI
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic validation
        run: |
          echo "Running minimal validation..."
          # ファイルの存在確認
          ls -la
          # package.jsonの確認
          if [ -f "package.json" ]; then
            echo "✅ package.json found"
          fi
          # Pythonファイルの基本チェック
          find . -name "*.py" -type f -exec python3 -m py_compile {} \; 2>&1 | head -20 || true
          echo "✅ Basic checks passed"