apiVersion: v1
kind: ConfigMap
metadata:
  name: shopify-config
  namespace: shopify-integration
data:
  store-url: "https://your-store.myshopify.com"
  api-version: "2023-10"
  rate-limit-calls: "2"
  rate-limit-period: "1"
  batch-size: "250"
  cache-ttl: "300"
  max-retries: "3"
  retry-delay: "1"
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: shopify-integration
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        gzip on;
        gzip_disable "msie6";
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/atom+xml image/svg+xml;

        upstream api {
            server shopify-integration-api:80;
        }

        server {
            listen 80;
            server_name _;

            location / {
                proxy_pass http://api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 300s;
                proxy_connect_timeout 75s;
            }

            location /health {
                proxy_pass http://api/health;
                access_log off;
            }
        }
    }
