apiVersion: v1
kind: Service
metadata:
  name: shopify-integration-api
  namespace: shopify-integration
  labels:
    app: shopify-integration
    component: api
spec:
  selector:
    app: shopify-integration
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: shopify-integration-api-external
  namespace: shopify-integration
  labels:
    app: shopify-integration
    component: api
spec:
  selector:
    app: shopify-integration
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: ClientIP
