version: '3.8'

services:
  yaml-rule-engine:
    build: .
    ports:
      - "3456:3456"
    environment:
      - NODE_ENV=test
      - PROMETHEUS_ENABLED=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3456/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - prometheus
      - grafana
    networks:
      - cerberus-network

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - cerberus-network

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=cerberus123
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - ./config/grafana-dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - ./config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - cerberus-network

  # ワーカー3のPrometheusシミュレーター
  worker3-simulator:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - cerberus-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  cerberus-network:
    driver: bridge