version: '3.8'

services:
  # Frontend React App
  frontend:
    build:
      context: ..
      dockerfile: deployment/docker/Dockerfile
    container_name: conea-frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - conea-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API (placeholder)
  backend:
    image: nginx:alpine
    container_name: conea-backend
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - conea-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  conea-network:
    driver: bridge

volumes:
  ssl-certs: