version: '3.8'

services:
  # MultiLLM APIサーバー
  multi-llm-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - ollama-service
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - multi-llm-network

  # Ollamaサーバー（ローカルLLM用）
  ollama-service:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - multi-llm-network

volumes:
  ollama-data:

networks:
  multi-llm-network:
    driver: bridge