name: Claude Reviewer
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    # メンションされたのがボットでないことを確認
    if: github.event.sender.type != 'Bot'
    runs-on: ubuntu-latest
    permissions:
        contents: 'write'
        pull-requests: 'write'
        issues: 'write'
        id-token: 'write'

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: 'Authenticate to Google Cloud'
          id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
              workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
              service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

        - name: 'Run Claude Code Review'
          id: claude
          uses: anthropics/claude-code-action@beta
          with:
              use_vertex: "true"
              model: "claude-sonnet-4@20250514"
              github_token: ${{ secrets.GENTA_PAT || secrets.GITHUB_TOKEN }} 