name: Claude Reviewer

on:
  issue_comment:
    types: [created]

permissions:
  contents: 'write'
  pull-requests: 'write'
  issues: 'write'
  id-token: 'write'

jobs:
  claude_reviewer:
    # ボットからのコメントは無視し、コメントに '@claude' が含まれている場合のみ実行
    if: |
      github.event.sender.type != 'Bot' &&
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. GitHub Appを使って一時的なトークンを生成
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # 2. GCPへ認証
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # 3. Claudeアクションを実行
      - name: 'Run Claude Code Review'
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          use_vertex: "true"
          model: "claude-3.5-sonnet@20240620"
          trigger_phrase: '@claude'
        env:
          CLOUD_ML_REGION: "us-east5"

      - name: 'Run Claude Code Review'
        uses: anthropic-ai/claude-code-reviewer-action@v1 # 正しいアクションを指定
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: "unused" # Workload Identityを使用するため不要
          CLOUD_ML_REGION: "us-east5"
        with:
          # 最新の高性能モデルを指定
          model_name: "claude-3.5-sonnet@20240620"
          # PRへのコメントか、Issueへのコメントかで動作を分岐
          review_rules_pr: |
            respond_only_if_code_changes: true
            approve_if_no_changes: true
          create_pr_from_issue: true # Issueの場合、PRを自動作成
          trigger_phrase: '@claude' 