name: Claude Code Review
on:
    issue_comment:
        types: [created]
    pull_request_review_comment:
        types: [created]

jobs:
    claude:
        # PRへのコメントで、ボット以外のユーザーが「@claude」とメンションした場合に実行
        if: |
            github.event.sender.type != 'Bot' &&
            contains(github.event.comment.body, '@claude')
        runs-on: ubuntu-latest
        permissions:
            contents: 'write'
            pull-requests: 'write'
            issues: 'write'
            id-token: 'write'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Claudeが全ての履歴を読めるようにするため

            - name: 'Authenticate to Google Cloud'
              id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                  workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

            - name: 'Run Claude Code via Vertex AI'
              id: claude
              uses: anthropics/claude-code-action@beta
              with:
                  use_vertex: "true"
                  model: "claude-sonnet-4@20250514"
                  github_token: ${{ secrets.GENTA_PAT || secrets.GITHUB_TOKEN }} 