name: 'PR Automation: Smart Review & Final Merge'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # === Job 1: AIレビューと内容判定（ゲートキーパー） ===
  ai_review_gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0 

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Run Claude Review Action'
        continue-on-error: true
        uses: zbeekman/claude-pr-review-action@v1
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROMPT_FILE_PATH: 'docs/prompts/project_guidelines/comprehensive_development_guidelines.md'

      - name: 'Wait for review comment to be posted'
        run: sleep 20

      - name: 'Check AI Review Result (Gatekeeper)'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          # ボット名をリポジトリ変数から取得し、なければ'claude-bot'をデフォルト値とする
          BOT_NAME: ${{ vars.AI_BOT_NAME || 'claude-bot' }}
        run: |
          # スクリプトがエラーで停止するように設定を追加
          set -euo pipefail

          # jqに安全に変数を渡すために--argを使用
          COMMENT_BODY=$(gh pr view $PR_NUMBER --json comments --jq --arg BOT_NAME "$BOT_NAME" '.comments[] | select(.author.login == $BOT_NAME) | .body' | tail -n 1)
          
          if [ -z "$COMMENT_BODY" ]; then
            echo "❌ Could not find a review comment from the AI bot ($BOT_NAME)."
            exit 1
          fi

          echo "Found comment from AI: $COMMENT_BODY"
          
          if echo "$COMMENT_BODY" | grep -q -e "推奨しません" -e "修正が必要です" -e "改善提案"; then
            echo "❌ AI review requested changes. This PR will not be merged automatically."
            exit 1
          else
            echo "✅ AI review approved. This check is successful."
            exit 0
          fi
          
  # === Job 2: 自動マージ実行（最終的な門番） ===
  automerge:
    runs-on: ubuntu-latest
    # 【最重要】AIレビューと、"必須"のCIジョブがすべて完了するのを待つ
    needs: 
      - ai_review_gatekeeper
      # --- ▼ ここに必須のCIジョブ名を追加してください ▼ ---
      # 例：E2EテストやLintチェックなど。実際のジョブ名に合わせてください。
      # - 'E2E Validation / e2e-tests'
      # - 'PR Validation / frontend-validation'
      # --- ▲ ここまで ▲ ---

    # 先行するすべてのジョブが成功した場合のみ、このジョブを実行
    if: success()

    steps:
      - name: 'Enable auto-merge for PR'
        uses: peter-evans/enable-auto-merge-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge