name: Claude Reviewer

on:
  issue_comment:
    types: [created]

permissions:
  contents: 'write'
  pull-requests: 'write'
  issues: 'write'
  id-token: 'write'

jobs:
  claude_reviewer:
    if: |
      github.event.sender.type != 'Bot' &&
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: 'Run Claude Code Review'
        id: claude-code
        uses: anthropics/claude-code-action@beta
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          use_vertex: "true"
          model: "claude-3.5-sonnet@20240620"
          trigger_phrase: '@claude'
        env:
          CLOUD_ML_REGION: "us-east5"
          ANTHROPIC_VERTEX_PROJECT_ID: ${{ steps.auth.outputs.project_id }}

      - name: Display Claude Execution Output
        if: always()
        run: |
          echo "Claude execution output file path is ${{ steps.claude-code.outputs.execution_file }}"
          echo "-------------------------------------"
          cat ${{ steps.claude-code.outputs.execution_file }}