name: Conea Sync Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/sync/**'
      - 'tests/sync/**'
      - 'requirements*.txt'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/sync/**'
      - 'tests/sync/**'
      - 'requirements*.txt'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the workflow with debug logging'
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run unit tests
      run: |
        pytest tests/sync/test_sync_models.py tests/sync/test_conea_sync.py tests/sync/test_conea_sync_tasks.py -v
    
    - name: Run integration tests
      run: |
        pytest tests/sync/test_integration.py -v
    
    - name: Generate coverage report
      run: |
        python -m pytest tests/sync --cov=src.sync --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: conea-sync
        name: codecov-conea-sync
        fail_ci_if_error: false
        verbose: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy
    
    - name: Lint with flake8
      run: |
        flake8 src/sync tests/sync --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Check formatting with black
      run: |
        black --check src/sync tests/sync
    
    - name: Check imports with isort
      run: |
        isort --check-only --profile black src/sync tests/sync