name: Frontend Main CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend-v2/**'
      - '.github/workflows/frontend-main-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend-v2/**'
      - '.github/workflows/frontend-main-ci.yml'

env:
  NODE_VERSION: '20'
  WORKING_DIRECTORY: 'frontend-v2'

jobs:
  test:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Run TypeScript type checking
        run: npx tsc --noEmit
      
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Run tests (if available)
        run: |
          if npm run --silent test 2>/dev/null; then
            npm run test
          else
            echo "No test script found, skipping tests"
          fi
        # テストが存在する場合は失敗時にパイプラインを停止させる
        # テストスクリプトが未実装の場合のみスキップを許可
      
      - name: Build Storybook
        run: npm run build-storybook
        env:
          NODE_ENV: production
      
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      
      - name: Start Storybook for tests
        run: |
          npm run storybook &
          STORYBOOK_PID=$!
          echo "STORYBOOK_PID=$STORYBOOK_PID" >> $GITHUB_ENV
          npx wait-on http://127.0.0.1:6006 --timeout 60000
      
      - name: Run Storybook test runner
        run: npm run test-storybook
        env:
          STORYBOOK_URL: http://127.0.0.1:6006
      
      - name: Run Playwright E2E tests for Storybook
        run: npx playwright test tests/storybook/
        env:
          STORYBOOK_URL: http://127.0.0.1:6006
      
      - name: Stop Storybook
        if: always()
        run: |
          if [ -n "$STORYBOOK_PID" ]; then
            kill $STORYBOOK_PID || true
          fi
      
      - name: Upload Playwright test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-${{ github.sha }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7
      
      - name: Start Next.js for Lighthouse CI
        run: |
          npm start &
          APP_PID=$!
          echo "APP_PID=$APP_PID" >> $GITHUB_ENV
          npx wait-on http://localhost:3000 --timeout 60000
      
      - name: Run Lighthouse CI
        run: npm run lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_UPLOAD_TARGET: temporary-public-storage
      
      - name: Stop Next.js
        if: always()
        run: |
          if [ -n "$APP_PID" ]; then
            kill $APP_PID || true
          fi
      
      - name: Upload Lighthouse results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results-${{ github.sha }}
          path: |
            .lighthouseci/
          retention-days: 7
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ github.sha }}
          path: ${{ env.WORKING_DIRECTORY }}/.next/
          retention-days: 1
      
      - name: Upload Storybook build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-build-${{ github.sha }}
          path: ${{ env.WORKING_DIRECTORY }}/storybook-static/
          retention-days: 1

  deploy-storybook:
    name: Deploy Storybook
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download Storybook build artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-build-${{ github.sha }}
          path: ${{ env.WORKING_DIRECTORY }}/storybook-static/
      
      - name: Deploy Storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.WORKING_DIRECTORY }}/storybook-static
          destination_dir: storybook/${{ github.ref == 'refs/heads/main' && 'main' || 'develop' }}
          
      - name: Comment Storybook URL on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            const storybookUrl = `https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/storybook/${branch}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 📚 Storybook Preview
              
              Storybook has been deployed and is available at:
              
              🔗 **[View Storybook](${storybookUrl})**
              
              This preview includes all components and their stories updated in this PR.`
            })
      
      - name: Notify Storybook deployment
        if: success()
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          STORYBOOK_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/storybook/$BRANCH_NAME"
          echo "📚 Storybook deployed successfully!"
          echo "🔗 Storybook URL: $STORYBOOK_URL"

  deploy-staging:
    name: Deploy to Staging
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    environment: staging
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build for staging
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{ secrets.STAGING_API_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
      
      - name: Setup Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: --version
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Deploy to Firebase Hosting (Staging)
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:app-staging --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      
      - name: Run post-deployment health check
        run: |
          sleep 30
          # ヘルスチェックエンドポイントでバックエンドAPI疎通確認と主要機能の動作確認を実施
          curl -f ${{ secrets.STAGING_FRONTEND_URL }}/api/health || exit 1
        # ステージング環境でのヘルスチェック失敗は重要な問題として扱う
      
      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Frontend deployed successfully to staging"
          echo "🔗 Staging URL: ${{ secrets.STAGING_FRONTEND_URL }}"
      
      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Frontend deployment to staging failed"
          exit 1

  deploy-production:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build for production
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{ secrets.PRODUCTION_API_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.PRODUCTION_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PRODUCTION_SUPABASE_ANON_KEY }}
      
      - name: Setup Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: --version
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Deploy to Firebase Hosting (Production)
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:app-production --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      
      - name: Run post-deployment health check
        run: |
          sleep 30
          curl -f ${{ secrets.PRODUCTION_FRONTEND_URL }}/api/health || exit 1
      
      - name: Notify deployment success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `✅ Frontend deployed successfully to production\n🔗 Production URL: ${{ secrets.PRODUCTION_FRONTEND_URL }}\n📦 Commit: ${{ github.sha }}\n👤 Author: ${{ github.actor }}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      - name: Notify deployment failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: 'danger',
                text: `❌ Frontend deployment to production failed\n📦 Commit: ${{ github.sha }}\n👤 Author: ${{ github.actor }}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run security audit
        run: npm audit --audit-level=moderate
        # プロダクションセキュリティ基準：moderate以上の脆弱性でパイプライン停止
      
      - name: Run dependency check with enforcement
        run: |
          npx audit-ci --moderate
        # セキュリティポリシー：moderate以上の脆弱性は必ず修正が必要